#ifndef FLASH_SAVE_H_
#define FLASH_SAVE_H_
#include "stm32f4xx.h"


extern UCHAR8 g_ucFlashFlag;
extern UCHAR8 g_ucFlashWrongNum;
extern SINT32 g_siFlashValue[];


/* Base address of the Flash sectors */
#define ADDR_FLASH_SECTOR_0     ((uint32_t)0x08000000) /* Base @ of Sector 0, 16 Kbytes */
#define ADDR_FLASH_SECTOR_1     ((uint32_t)0x08004000) /* Base @ of Sector 1, 16 Kbytes */
#define ADDR_FLASH_SECTOR_2     ((uint32_t)0x08008000) /* Base @ of Sector 2, 16 Kbytes */
#define ADDR_FLASH_SECTOR_3     ((uint32_t)0x0800C000) /* Base @ of Sector 3, 16 Kbytes */
#define ADDR_FLASH_SECTOR_4     ((uint32_t)0x08010000) /* Base @ of Sector 4, 64 Kbytes */
#define ADDR_FLASH_SECTOR_5     ((uint32_t)0x08020000) /* Base @ of Sector 5, 128 Kbytes */
#define ADDR_FLASH_SECTOR_6     ((uint32_t)0x08040000) /* Base @ of Sector 6, 128 Kbytes */
#define ADDR_FLASH_SECTOR_7     ((uint32_t)0x08060000) /* Base @ of Sector 7, 128 Kbytes */
#define ADDR_FLASH_SECTOR_8     ((uint32_t)0x08080000) /* Base @ of Sector 8, 128 Kbytes */
#define ADDR_FLASH_SECTOR_9     ((uint32_t)0x080A0000) /* Base @ of Sector 9, 128 Kbytes */
#define ADDR_FLASH_SECTOR_10    ((uint32_t)0x080C0000) /* Base @ of Sector 10, 128 Kbytes */
#define ADDR_FLASH_SECTOR_11    ((uint32_t)0x080E0000) /* Base @ of Sector 11, 128 Kbytes */


#define SAVE_DATA_START_ADDR 	  	ADDR_FLASH_SECTOR_11



#define  OFST_COFF_OMNI_Q_ADDR		  	0
#define  OFST_OMNI_Q_ADDR		  	1

#define  OFST_COFF_OMNI_MEMS_Q_ADDR		4
#define  OFST_OMNI_MEMS_Q_ADDR	5

#define OFST_HORMOTOR_POT1_ADDR			8
#define OFST_HORMOTOR_POT2_ADDR			9

#define OFST_RED_CATCHBANPATH_RES1_X		12
#define OFST_RED_CATCHBANPATH_RES1_Y		13
#define OFST_RED_CATCHBANPATH_RES1_Q		14

#define OFST_RED_RELEASEBANPATH_RES1_X		16
#define OFST_RED_RELEASEBANPATH_RES1_Y		17
#define OFST_RED_RELEASEBANPATH_RES1_Q		18



#define OFST_RED_CATCHBANPATH_RES2_X		20
#define OFST_RED_CATCHBANPATH_RES2_Y		21
#define OFST_RED_CATCHBANPATH_RES2_Q		22

#define OFST_RED_RELEASEBANPATH_RES2_X		24
#define OFST_RED_RELEASEBANPATH_RES2_Y		25
#define OFST_RED_RELEASEBANPATH_RES2_Q		26




#define OFST_RED_CATCHBANPATH_RES3_X		28
#define OFST_RED_CATCHBANPATH_RES3_Y		29
#define OFST_RED_CATCHBANPATH_RES3_Q		30

#define OFST_RED_RELEASEBANPATH_RES3_X		32
#define OFST_RED_RELEASEBANPATH_RES3_Y		33
#define OFST_RED_RELEASEBANPATH_RES3_Q		34



#define OFST_BLUE_CATCHBANPATH_RES1_X		36
#define OFST_BLUE_CATCHBANPATH_RES1_Y		37
#define OFST_BLUE_CATCHBANPATH_RES1_Q		38

#define OFST_BLUE_RELEASEBANPATH_RES1_X		40
#define OFST_BLUE_RELEASEBANPATH_RES1_Y		41
#define OFST_BLUE_RELEASEBANPATH_RES1_Q		42



#define OFST_BLUE_CATCHBANPATH_RES2_X		44
#define OFST_BLUE_CATCHBANPATH_RES2_Y		45
#define OFST_BLUE_CATCHBANPATH_RES2_Q		46

#define OFST_BLUE_RELEASEBANPATH_RES2_X		48
#define OFST_BLUE_RELEASEBANPATH_RES2_Y		49
#define OFST_BLUE_RELEASEBANPATH_RES2_Q		50




#define OFST_BLUE_CATCHBANPATH_RES3_X		52
#define OFST_BLUE_CATCHBANPATH_RES3_Y		53
#define OFST_BLUE_CATCHBANPATH_RES3_Q		54

#define OFST_BLUE_RELEASEBANPATH_RES3_X		56
#define OFST_BLUE_RELEASEBANPATH_RES3_Y		57
#define OFST_BLUE_RELEASEBANPATH_RES3_Q		58



#define OFST_BLUE_GOBASKETPATH_RES4_X		60
#define OFST_BLUE_GOBASKETPATH_RES4_Y		61
#define OFST_BLUE_GOBASKETPATH_RES4_Q		62

#define OFST_RED_GOBASKETPATH_RES4_X		64
#define OFST_RED_GOBASKETPATH_RES4_Y		65
#define OFST_RED_GOBASKETPATH_RES4_Q	66

#define OFST_BLUE_CATCHMIDDLEBAN_RES1	68
#define OFST_BLUE_CATCHMIDDLEBAN_RES2	69
#define OFST_BLUE_CATCHMIDDLEBAN_RES3	70
#define OFST_BLUE_CATCHTOPBAN				71

#define OFST_RED_CATCHMIDDLEBAN_RES1		74
#define OFST_RED_CATCHMIDDLEBAN_RES2		75
#define OFST_RED_CATCHMIDDLEBAN_RES3		76
#define OFST_RED_CATCHTOPBAN				77
#define OFST_RED_OR_BLUE					80

#define  MAX_FLASH_LEN   100

extern UCHAR8 SaveOneWord32(SINT32 siData,UINT32 uiWriteAddr);
extern SSHORT16 GetOneShort16(UINT32 uiReadAddr);
extern SINT32	GetOneInt32(UINT32 uiReadAddr);

extern UCHAR8 SaveAllWord32(void);

#endif
